/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronaproperties;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Melvin K
 */
public class ComputationMenu extends javax.swing.JFrame {
    static boolean computeDep = false;
    static boolean computeAppre = false;
    private int xMouse;
    private int yMouse;
    private static String output = "";
    private static DecimalFormat df = new DecimalFormat("R ###,###,###,###,###,###.00");
    /**
     * Creates new form ReadPropByMenu
     */
    public ComputationMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        btnHome = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnComparativeViews = new javax.swing.JButton();
        btnComputation = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnCompAppreciation = new javax.swing.JButton();
        btnCompDepreciation = new javax.swing.JButton();
        Footer = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(63, 81, 181));
        kGradientPanel1.setkStartColor(new java.awt.Color(144, 202, 249));

        Header.setBackground(new java.awt.Color(0, 31, 63));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Under Authority", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Corona properties");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Multiplication_24px_2.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Minus_24px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        Header.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Menu_96px_2.png"))); // NOI18N
        Header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Help_24px.png"))); // NOI18N
        Header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        btnLogout.setBackground(java.awt.Color.lightGray);
        btnLogout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        Header.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 80, -1));

        kGradientPanel3.setkEndColor(new java.awt.Color(144, 202, 249));
        kGradientPanel3.setkStartColor(new java.awt.Color(88, 119, 202));

        btnHome.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(88, 119, 202));
        btnHome.setText("Home");
        btnHome.setAlignmentX(5.0F);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N

        btnAdd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(88, 119, 202));
        btnAdd.setText("Add Property");
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDisplay.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDisplay.setForeground(new java.awt.Color(88, 119, 202));
        btnDisplay.setText("View Property");
        btnDisplay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnComparativeViews.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnComparativeViews.setForeground(new java.awt.Color(88, 119, 202));
        btnComparativeViews.setText("Comparative Views");
        btnComparativeViews.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComparativeViews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComparativeViewsActionPerformed(evt);
            }
        });

        btnComputation.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnComputation.setForeground(new java.awt.Color(88, 119, 202));
        btnComputation.setText("Computations");
        btnComputation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComputation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputationActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(88, 119, 202));
        btnUpdate.setText("Update Property");
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(88, 119, 202));
        btnDelete.setText("Delete Property");
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(kGradientPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup().addContainerGap().addGroup(kGradientPanel3Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel3Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14).addComponent(jLabel17).addComponent(jLabel15))
                                .addComponent(jLabel16).addComponent(jLabel19).addComponent(jLabel18))
                        .addComponent(jLabel20)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btnComparativeViews, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnComputation, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))));
        kGradientPanel3Layout.setVerticalGroup(kGradientPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup().addContainerGap()
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17).addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDisplay).addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnComparativeViews).addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnComputation).addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnUpdate).addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDelete).addComponent(jLabel18))
                        .addContainerGap()));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Computation Menu");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 1, new java.awt.Color(0, 0, 0)));

        btnCompAppreciation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCompAppreciation.setForeground(new java.awt.Color(88, 119, 202));
        btnCompAppreciation.setText("Computate Appreciation");
        btnCompAppreciation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompAppreciationActionPerformed(evt);
            }
        });

        btnCompDepreciation.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCompDepreciation.setForeground(new java.awt.Color(88, 119, 202));
        btnCompDepreciation.setText("Computate Depreciation");
        btnCompDepreciation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompDepreciationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(kGradientPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCompDepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, 257,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32).addComponent(btnCompAppreciation)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
        kGradientPanel1Layout.setVerticalGroup(kGradientPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(30, Short.MAX_VALUE))
                                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(kGradientPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnCompDepreciation,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 176,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnCompAppreciation,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 176,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(80, 80, 80)))));

        Footer.setBackground(new java.awt.Color(0, 31, 63));
        Footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("All rights reserved: ©CP");
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        Footer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(Footer,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel5MousePressed

        int option = JOptionPane.showConfirmDialog(null, "Do you really want to exit?", "Are you sure",
                JOptionPane.YES_NO_OPTION);
        /*
         * 0 = yes 1 = no
         */
        if (option == 0) {
            Auth.signOut();
            System.exit(0);
        }
    }// GEN-LAST:event_jLabel5MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel10MousePressed

        this.setState(Login.ICONIFIED);
    }// GEN-LAST:event_jLabel10MousePressed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogoutActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Do you really want to log out?", "Are you sure",
                JOptionPane.YES_NO_OPTION);
        /*
         * 0 = yes 1 = no
         */
        if (option == 0) {
            Auth.signOut();
            System.exit(0);
        }
    }// GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHomeActionPerformed
        Auth.houseCleaning();

        // Close this menu
        this.dispose();

        // Back to main menu
        MainMenu menu = new MainMenu();

        menu.setTitle("Corona Main Menu");
        SetJFrameIcon setJFrameIcon = new SetJFrameIcon(menu);

    }// GEN-LAST:event_btnHomeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
//        this.dispose();
//        CreateProp.createSome();
        Auth.createSomeProp = true;
        this.dispose();
        CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
        SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);

    }// GEN-LAST:event_btnAddActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDisplayActionPerformed
//        this.dispose();
//        ReadPropAll.readAll();
        Auth.readPropAll = true;
        this.dispose();
        CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
        SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);

    }// GEN-LAST:event_btnDisplayActionPerformed

    private void btnComparativeViewsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnComparativeViewsActionPerformed
        this.dispose();

        // Open ComparativeViewsMenu
        ComparativeViewsMenu aComparativeViewsMenu = new ComparativeViewsMenu();

        aComparativeViewsMenu.setTitle("Corona Comparative View");
        SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aComparativeViewsMenu);

    }// GEN-LAST:event_btnComparativeViewsActionPerformed

    private void btnComputationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnComputationActionPerformed
        // this.dispose();
        //
        // //Open ComputationMenu
        // ComputationMenu aComputationMenu = new ComputationMenu();
        //
        // aComputationMenu.setTitle("Corona Computation Menu");
        // SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aComputationMenu);
        //
        //
    }// GEN-LAST:event_btnComputationActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
//        this.dispose();
//        UpdateProp.updateSome();
        Auth.updateSomeProp = true;
        this.dispose();
        CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
        SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);

    }// GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
//        this.dispose();
//        DeleteProp.deleteSome();
        Auth.deleteSomeProp = true;
        this.dispose();
        CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
        SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);

    }// GEN-LAST:event_btnDeleteActionPerformed

    private void btnCompAppreciationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCompAppreciationActionPerformed
        try {
            String searchString = JOptionPane.showInputDialog("Enter property you want to compute appreciation on: ");
            computeAppre = true;
            CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
            // Searching
            if (!searchString.isEmpty()) {
                double currentValue = aCrudViewTemplate.search(searchString);

                String r = JOptionPane.showInputDialog("Enter rate of appreciation: ");
                String t = JOptionPane.showInputDialog("Enter number of year(s) of appreciation: ");
                if (!r.isEmpty() && !t.isEmpty()) {
                    this.dispose();
                    // Computing
                    computeAppre(currentValue, r, t);
                    aCrudViewTemplate.setTitle("Computations");
                    SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);
                    displayData();
                }
            }
            computeAppre = false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error ocurred!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnCompAppreciationActionPerformed

    private void btnCompDepreciationActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String searchString = JOptionPane.showInputDialog("Enter property you want to compute depreciation on: ");
            computeDep = true;

            CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
            // Searching
            if (!searchString.isEmpty()) {
                double currentValue = aCrudViewTemplate.search(searchString);

                String r = JOptionPane.showInputDialog("Enter rate of depreciation: ");
                String t = JOptionPane.showInputDialog("Enter number of year(s) of depreciation: ");
                if (!r.isEmpty() && !t.isEmpty()) {
                    this.dispose();
                    // Computing
                    computeDep(currentValue, r, t);
                    aCrudViewTemplate.setTitle("Computations");
                    SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);
                    displayData();
                }
            }
            computeDep = false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error ocurred!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void formMouseDragged(java.awt.event.MouseEvent evt)// GEN-FIRST:event_formMouseDragged
    {// GEN-HEADEREND:event_formMouseDragged
        setOpacity((float) 0.7);
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }// GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt)// GEN-FIRST:event_formMousePressed
    {// GEN-HEADEREND:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }// GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt)// GEN-FIRST:event_formMouseReleased
    {// GEN-HEADEREND:event_formMouseReleased
        setOpacity((float) 0.9);
    }// GEN-LAST:event_formMouseReleased

    private static String computeDep(double currentValue, String r, String t) {
        double depreciation = (currentValue * Double.parseDouble(t) / 100 * Integer.parseInt(t));
        double valueAfterDep = currentValue - depreciation;

        output = "";

        if (valueAfterDep < depreciation) {
            output = "This property no longer has any worth";
        } else {
            output = "Old value: " + df.format(currentValue) + "\n\nAfter a depreciation rate of " + r + "% for " + t
                    + " years" + "\n\nThe properties' worth: " + df.format(valueAfterDep);
        }
        return output;
    }

    private static void displayData() {
        JOptionPane.showMessageDialog(null, output);
    }

    private static String computeAppre(double currentValue, String r, String t) {
        double appreciation = (currentValue * Double.parseDouble(r) / 100 * Double.parseDouble(t));
        double valueAfterAppre = currentValue + appreciation;

        output = "";

        output = "This property no longer has any worth";

        output = "Old value: " + df.format(currentValue) + "\n\nAfter an appreciation rate of " + r + "% for " + t
                + " years" + "\n\nThe properties' worth: " + df.format(valueAfterAppre);

        return output;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputationMenu().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCompAppreciation;
    private javax.swing.JButton btnCompDepreciation;
    private javax.swing.JButton btnComparativeViews;
    private javax.swing.JButton btnComputation;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel3;
    // End of variables declaration//GEN-END:variables
}
