/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronaproperties;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Melvin K
 */
public class ComputationMenu extends javax.swing.JFrame {
    static boolean computeDep = false;
    static boolean computeAppre = false;
    private static String output = "";
    private static DecimalFormat df = new DecimalFormat("R ###,###,###,###,###,###.00");
    /**
     * Creates new form ReadPropByMenu
     */
    public ComputationMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCompDepreciation = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblHeading = new javax.swing.JLabel();
        btnCompAppreciation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        btnCompDepreciation.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        btnCompDepreciation.setText("Computate Depreciation");
        btnCompDepreciation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompDepreciationActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblHeading.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        lblHeading.setText("Corona Computation Menu");

        btnCompAppreciation.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        btnCompAppreciation.setText("Computate Appreciation");
        btnCompAppreciation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompAppreciationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(btnCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(lblHeading))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCompDepreciation)
                            .addComponent(btnCompAppreciation))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHeading)
                .addGap(122, 122, 122)
                .addComponent(btnCompDepreciation)
                .addGap(124, 124, 124)
                .addComponent(btnCompAppreciation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Do you really want to cancel?", "Are you sure", JOptionPane.YES_NO_OPTION);
        /*
         * 0 = yes
         * 1 = no
         */
        if (option == 0) {
            this.dispose();

            //Back to main menu
            MainMenu menu = new MainMenu();

            menu.setTitle("Corona Main Menu");
            SetJFrameIcon setJFrameIcon = new SetJFrameIcon(menu);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCompDepreciationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompDepreciationActionPerformed
        try {
            String searchString = JOptionPane.showInputDialog("Enter property you want to compute depreciation on: ");
            computeDep = true;

            CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
            //Searching
            if (!searchString.isEmpty()) {
                double currentValue = aCrudViewTemplate.search(searchString);

                String r = JOptionPane.showInputDialog("Enter rate of depreciation: ");
                String t = JOptionPane.showInputDialog("Enter number of year(s) of depreciation: ");
                if (!r.isEmpty() && !t.isEmpty()) {
                    this.dispose();
                    //Computing
                    computeDep(currentValue, r, t);
                    aCrudViewTemplate.setTitle("Computations");
                    SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);
                    displayData();
                }
            }
            computeDep = false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error ocurred!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCompDepreciationActionPerformed

    private static String computeDep(double currentValue, String r, String t) {
        double depreciation = (currentValue * Double.parseDouble(t) / 100 * Integer.parseInt(t));
        double valueAfterDep = currentValue - depreciation;

        output = "";

        if (valueAfterDep < depreciation) {
            output = "This property no longer has any worth";
        } else {
            output = "Old value: " + df.format(currentValue)
                    + "\n\nAfter a depreciation rate of " + r + "% for " + t + " years"
                    + "\n\nThe properties' worth: "
                    + df.format(valueAfterDep);
        }
        return output;
    }

    private static void displayData() {
        JOptionPane.showMessageDialog(null, output);
    }

    private void btnCompAppreciationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompAppreciationActionPerformed
        try {
            String searchString = JOptionPane.showInputDialog("Enter property you want to compute appreciation on: ");
            computeAppre = true;
            CRUDViewTemplate aCrudViewTemplate = new CRUDViewTemplate();
            //Searching
            if (!searchString.isEmpty()) {
                double currentValue = aCrudViewTemplate.search(searchString);

                String r = JOptionPane.showInputDialog("Enter rate of appreciation: ");
                String t = JOptionPane.showInputDialog("Enter number of year(s) of appreciation: ");
                if (!r.isEmpty() && !t.isEmpty()) {
                    this.dispose();
                    //Computing
                    computeDep(currentValue, r, t);
                    aCrudViewTemplate.setTitle("Computations");
                    SetJFrameIcon setJFrameIcon = new SetJFrameIcon(aCrudViewTemplate);
                    displayData();
                }
            }
            computeAppre = false;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error ocurred!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCompAppreciationActionPerformed

    static String computeAppre(double currentValue, double r, int t) {
        double appreciation = (currentValue * r / 100 * t);
        double valueAfterAppre = currentValue + appreciation;

        output = "";

        output = "This property no longer has any worth";

        output = "Old value: " + df.format(currentValue)
                + "\n\nAfter an appreciation rate of " + r + "% for " + t + " years"
                + "\n\nThe properties' worth: "
                + df.format(valueAfterAppre);

        return output;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputationMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComputationMenu().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCompAppreciation;
    private javax.swing.JButton btnCompDepreciation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeading;
    // End of variables declaration//GEN-END:variables
}
