/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | lates
 * and open the template in the editor.
 */
package coronaproperties;

import javax.swing.JOptionPane;

/**
 *
 * @author MightyBeatz
 */
public class Login extends javax.swing.JFrame
{
    private boolean register = false;
    private int xMouse;
    private int yMouse;
    /**
     * Creates new form Login
     */
    public Login()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jCheckBoxShowPass = new javax.swing.JCheckBox();
        txtPass = new javax.swing.JPasswordField();
        lblRegister = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        lblForRegistration = new javax.swing.JLabel();
        txtForRegistration = new javax.swing.JPasswordField();
        txtForRegistration1 = new javax.swing.JPasswordField();
        lblForRegistration1 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                formMouseReleased(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(63, 81, 181));
        kGradientPanel1.setkStartColor(new java.awt.Color(144, 202, 249));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 31, 63));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(144, 202, 249));
        kGradientPanel2.setkStartColor(new java.awt.Color(88, 119, 202));

        lblTitle.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Login");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email: ");

        lblPass.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        lblPass.setText("Password: ");

        txtEmail.setBackground(new java.awt.Color(240, 240, 240));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmail.setMinimumSize(new java.awt.Dimension(64, 29));
        txtEmail.setOpaque(false);
        txtEmail.setPreferredSize(new java.awt.Dimension(327, 30));

        btnLogin.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px_1.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLoginActionPerformed(evt);
            }
        });

        jCheckBoxShowPass.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowPass.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jCheckBoxShowPass.setText("Show password");
        jCheckBoxShowPass.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBoxShowPassActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPass.setOpaque(false);
        txtPass.setPreferredSize(new java.awt.Dimension(327, 30));

        lblRegister.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Add_24px.png"))); // NOI18N
        lblRegister.setText("Don't have an account?");

        btnRegister.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegisterActionPerformed(evt);
            }
        });

        lblForRegistration.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        lblForRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblForRegistration.setText("Password: ");

        txtForRegistration.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtForRegistration.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtForRegistration.setOpaque(false);
        txtForRegistration.setPreferredSize(new java.awt.Dimension(327, 30));

        txtForRegistration1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtForRegistration1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtForRegistration1.setOpaque(false);
        txtForRegistration1.setPreferredSize(new java.awt.Dimension(327, 30));

        lblForRegistration1.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        lblForRegistration1.setForeground(new java.awt.Color(255, 255, 255));
        lblForRegistration1.setText("Re-enter Password: ");

        lblError.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(153, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblForRegistration1)
                    .addComponent(lblPass)
                    .addComponent(lblEmail)
                    .addComponent(lblForRegistration))
                .addGap(14, 14, 14)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(lblRegister)
                        .addGap(24, 24, 24)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxShowPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtForRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtForRegistration1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForRegistration)
                    .addComponent(txtForRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForRegistration1)
                    .addComponent(txtForRegistration1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxShowPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(37, 37, 37)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(lblRegister))
                .addContainerGap())
        );

        jPanel2.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 430));

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 600, 450));

        Header.setBackground(new java.awt.Color(0, 31, 63));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Under Authority", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Corona properties");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Multiplication_24px_2.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLabel5MousePressed(evt);
            }
        });
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Minus_24px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLabel10MousePressed(evt);
            }
        });
        Header.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Customer_96px.png"))); // NOI18N
        Header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Help_24px.png"))); // NOI18N
        Header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        kGradientPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!register)
        {
            //Capture email and password from GUI
            String remain = "";
            String fullName = String.valueOf(txtEmail.getText()).toUpperCase();
            String emailString = String.valueOf(txtPass.getPassword());
            String passString = String.valueOf(txtForRegistration.getPassword());
            String tempPassString = String.valueOf(txtForRegistration1.getPassword());
            //Checking for empty fields
            if (!fullName.isEmpty() || !emailString.isEmpty() || !passString.isEmpty() || !tempPassString.isEmpty())
            {
                //Checking if fullname has illegal characters
//                if (Validate.isWord(fullName))
//                {
                //Split first and last name
                String[] fullNameArray = fullName.trim().split("\\s+");

                //Get first name
                String tempFNameString = fullNameArray[0];

                //Converting First name to Title case
                char f = tempFNameString.charAt(0);
                String fN = String.valueOf(f);
                String fNameString = fN + (tempFNameString.substring(1, tempFNameString.length()).toLowerCase());

                //Get last name
                String tempLNameString = fullNameArray[1];

                char l = tempLNameString.charAt(0);
                String lN = String.valueOf(l);
                String lNameString = lN + (tempLNameString.substring(1, tempLNameString.length()).toLowerCase());

                System.out.println(fNameString + "\t" + lNameString + "\t" + emailString + "\t" + passString + "\t" + tempPassString);

//                //Check if passwords match
                if (passString.compareTo(tempPassString) == 0)
                {
                    //Checking if email and password meets minimum requirements

                    if (Validate.isEmail(emailString) && Validate.isPass(passString))
                    {
                        if (Auth.register(fNameString, lNameString, emailString, passString))
                        {
                            this.dispose();
                            Auth.openMenu();
                        } else
                        {
                            lblError.setText("Error occured!");
                        }
                    } else
                    {
                        lblError.setText("Email or Password does NOT meet min requirements!");
                    }
                } else
                {
                    lblError.setText("Password do NOT match!");
                }
//                } else
//                {
//                    lblError.setText("Fullname contains illegal characters!");
//                }
            } else
            {
                lblError.setText("One or more fields are empty!");
            }

        } else
        {
            //Capture email and password from GUI
            String emailString = String.valueOf(txtEmail.getText());
            String passString = String.valueOf(txtPass.getPassword());
            //Checking for empty fields
            if (!emailString.isEmpty() || !passString.isEmpty())
            {
                //Checking if email and password meets minimum requirements
                if (Validate.isEmail(emailString) && Validate.isPass(passString))
                {
                    if (Auth.login(emailString, passString))
                    {
                        this.dispose();
                        Auth.openMenu();
                    } else
                    {
                        lblError.setText("Email or Password is incorrect!");
                    }
                } else
                {
                    lblError.setText("Email or Password does NOT meet min requirements!");
                }
            } else
            {
                lblError.setText("One or more fields are empty!");
            }

        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jCheckBoxShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPassActionPerformed
        if (jCheckBoxShowPass.isSelected())
        {
            txtPass.setEchoChar('\u0000');
        } else
        {
            txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPassActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        whatAction();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed

        int option = JOptionPane.showConfirmDialog(null, "Do you really want to exit?", "Are you sure", JOptionPane.YES_NO_OPTION);
        /*
         * 0 = yes
         * 1 = no
         */
        if (option == 0)
        {
            Auth.signOut();
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed

        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel10MousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseDragged
    {//GEN-HEADEREND:event_formMouseDragged
        setOpacity((float) 0.7);
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMousePressed
    {//GEN-HEADEREND:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseReleased
    {//GEN-HEADEREND:event_formMouseReleased
        setOpacity((float) 0.9);
    }//GEN-LAST:event_formMouseReleased

    public void whatAction()
    {
        if (register)
        {
            //Clear text fields first
            txtEmail.setText("");
            txtPass.setText("");
            txtForRegistration.setText("");
            txtForRegistration1.setText("");

            //Adapt UI for registration
            lblTitle.setText("Register");
            btnLogin.setText("Register");
            lblRegister.setText("Already have an account?");
            btnRegister.setText("Login");
            lblError.setText("");

            lblEmail.setText("Full name: ");
            lblPass.setText("Email: ");

            txtPass.setEchoChar('\u0000');
            lblForRegistration.setVisible(true);
            txtForRegistration.setVisible(true);
            lblForRegistration1.setVisible(true);
            txtForRegistration1.setVisible(true);
            txtForRegistration.setEchoChar('*');
            txtForRegistration1.setEchoChar('*');
            jCheckBoxShowPass.setVisible(false);

            register = false;
        } else
        {
            //Clear text fields first
            txtEmail.setText("");
            txtPass.setText("");
            txtForRegistration.setText("");
            txtForRegistration1.setText("");

            //Adapt UI for login
            lblTitle.setText("Login");
            btnLogin.setText("Login");
            lblRegister.setText("No account?");
            btnRegister.setText("Register");
            lblError.setText("");

            lblEmail.setText("Email: ");
            lblPass.setText("Password: ");
            txtPass.setEchoChar('*');

            lblForRegistration.setVisible(false);
            txtForRegistration.setVisible(false);
            lblForRegistration1.setVisible(false);
            txtForRegistration1.setVisible(false);
            txtForRegistration1.setEchoChar('\u0000');
            jCheckBoxShowPass.setVisible(true);
            register = true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Login().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox jCheckBoxShowPass;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblForRegistration;
    private javax.swing.JLabel lblForRegistration1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtForRegistration;
    private javax.swing.JPasswordField txtForRegistration1;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
